### ISSUE TITLE
Bug: Oracle-on-Windows Plugin BUILD FAILED with different error using DVP 3.1.0 version.

### ISSUE THREAD

**Issue by ankurtyagi-sdk** [delphix/oracle-on-windows-plugin#2]
**Description:**
Observed the below issues during the "Oracle-on-window" plugin build using the latest DVP version 3.1.0.

Error**
```
dvp -vvv build -a /Users/ankur.tyagi/Delphix/toolkit/oracle-on-windows-0.1.0.json -c plugin_config.yml
Console logging configured with logging level 0
Build parameters include plugin_config: /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/plugin_config.yml, upload_artifact: /Users/ankur.tyagi/Delphix/toolkit/oracle-on-windows-0.1.0.json, generate_only: False
Validating plugin config file /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/plugin_config.yml
Reading plugin config file /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/plugin_config.yml
Validating plugin config file content : {'pluginType': 'STAGED', 'name': 'Oracle on Windows', 'language': 'PYTHON27', 'hostTypes': ['WINDOWS'], 'id': '202b2966-a67b-4657-bd9a-c901d7f654fb', 'version': '0.1.0', 'entryPoint': 'plugin_runner:plugin', 'srcDir': 'src', 'schemaFile': 'schema.json'}
Error: Additional properties are not allowed ('version' was unexpected) on ['additionalProperties']
Error: 'buildNumber' is a required property on ['required']
Validation failed on /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/plugin_config.yml. 
0 Warning(s). 2 Error(s) 
BUILD FAILED.
Traceback (most recent call last):
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 57, in command_error_handle
    yield
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 222, in build
    local_vsdk_root=local_vsdk_root)
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/commands/build.py", line 68, in build
    raise exceptions.BuildFailedError(err)
BuildFailedError: Error: Additional properties are not allowed ('version' was unexpected) on ['additionalProperties']
Error: 'buildNumber' is a required property on ['required']
Validation failed on /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/plugin_config.yml. 
0 Warning(s). 2 Error(s)
BUILD FAILED.
 
BUILD FAILED.
Traceback (most recent call last):
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 57, in command_error_handler
    yield
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 222, in build
    local_vsdk_root=local_vsdk_root)
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/commands/build.py", line 122, in build
    raise exceptions.BuildFailedError(err)
BuildFailedError: Error: No module named operations


0 Warning(s). 1 Error(s).
BUILD FAILED.
 
BUILD FAILED.
Traceback (most recent call last):
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/dvp2/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 57, in command_error_handler
    yield
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/dvp2/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 229, in build
    local_vsdk_root=local_vsdk_root)
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/dvp2/lib/python2.7/site-packages/dlpx/virtualization/_internal/commands/build.py", line 77, in build
    raise exceptions.BuildFailedError(err)
BuildFailedError: Error: Additional properties are not allowed ('snapshotParametersDefinition' was unexpected) on ['additionalProperties']

Validation failed on /Users/ankur.tyagi/Delphix/vsdk-plugins/GitHub/oracle-on-windows-plugin/schema.json. 
0 Warning(s). 1 Error(s) 

BUILD FAILED.
 
BUILD FAILED.
Traceback (most recent call last):
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 57, in command_error_handler
    yield
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/cli.py", line 222, in build
    local_vsdk_root=local_vsdk_root)
  File "/Users/ankur.tyagi/Delphix/vsdk-plugins/vsdk/lib/python2.7/site-packages/dlpx/virtualization/_internal/commands/build.py", line 122, in build
    raise exceptions.BuildFailedError(err)
BuildFailedError: Error: Named argument mismatch in method linked_post_snapshot. Expected: ['staged_source', 'repository', 'source_config', 'optional_snapshot_parameters'], Found: ['staged_source', 'repository', 'source_config', 'snapshot_parameters'].
Error: Named argument mismatch in method restore_oracle_backup. Expected: ['staged_source', 'repository', 'source_config', 'optional_snapshot_parameters'], Found: ['staged_source', 'repository', 'source_config', 'snapshot_parameters'].

0 Warning(s). 2 Error(s). 

BUILD FAILED.
```

**Comment by ankurtyagi-sdk** [comment]
Modified the following files in the plugin for performing a successful build operation.

**Schema.json**
```
"snapshotParametersDefinition": {
       "type" : "object",
       "additionalProperties" : false,
       "properties" : {
           "resync" :
           {
               "type": "boolean",
               "prettyName": "Resynchronize dSource",
               "description": "Resynchronizing dSource will force a non-incremental load of data from the source. This operation is similar to creating a new dSource, but avoids duplicating storage requirements and maintains Timeflow history. Are you sure you want to Resynchronize this dSource?"
           }
       }
   },
```

**plugin_config.yml**
```
id: 202b2966-a67b-4657-bd9a-c901d7f654fb
name: Oracle on Windows
language: PYTHON27
hostTypes:
- WINDOWS
pluginType: STAGED
entryPoint: plugin_runner:plugin
srcDir: src
schemaFile: schema.json
buildNumber: 1.0.0
```

**plugin_runner.py** 

```
@plugin.linked.pre_snapshot()
def restore_oracle_backup(staged_source,repository,source_config,optional_snapshot_parameters):

    source_connection = staged_source.staged_connection
    parameters = staged_source.parameters

    if optional_snapshot_parameters.resync:
        return restore.initial_sync(source_connection,parameters,repository,source_config),
    else:
        return restore.incremental_sync(source_connection,parameters,repository,source_config)


@plugin.linked.post_snapshot()
def linked_post_snapshot(staged_source,repository,source_config,optional_snapshot_parameters):

    source_connection = staged_source.staged_connection
    parameters = staged_source.parameters

    return postSnapshot._make_ds_postsnapshot(source_connection,parameters,repository,source_config,optional_snapshot_parameters)
```
