### ISSUE TITLE
Bug: A problem was detected in the plugin Oracle on Windows for the operation Repository Discovery

### ISSUE THREAD

**Issue by ankurtyagi-sdk** [delphix/oracle-on-windows-plugin#3]
**Description:**
The issue is with the environment discovery operation when we build the "Oracle-on-windows" Plugin with the latest DVP version 3.1.0.

**Error**
`
Discovery of "Oracle on Windows" failed: A problem was detected in the plugin "Oracle on Windows" for the operation "Repository Discovery": The function run_powershell's argument 'command' was type 'NoneType' but should be of type 'basestring'. Traceback (most recent call last): File "./dlpx/virtualization/platform/_discovery.py", line 79, in _internal_repository File "./dlpx/virtualization/platform/_discovery.py", line 79, in _internal_repository File "./plugin_runner.py", line 31, in repository_discovery File "./plugin_runner.py", line 31, in repository_discovery File "./operations/discovery.py", line 17, in find_repos File "./operations/discovery.py", line 17, in find_repos File "./utils/executeScript.py", line 15, in execute_powershell File "./utils/executeScript.py", line 15, in execute_powershell File "./dlpx/virtualization/libs/libs.py", line 292, in run_powershell File "./dlpx/virtualization/libs/libs.py", line 292, in run_powershell
`

**Comment by ankurtyagi-sdk** [comment]
Added _ini_.py file under the following directories to resolve the issue observed during discovery operation with Oracle-on-windows plugin.

```
new file:   src/operations/__ini__.py       
new file:   src/resources/__ini__.py       
new file:   src/utils/__ini__.py 
```
The _ini_.py file makes Python treat directories containing it as modules.

Furthermore, this is the first file to be loaded in a module, so you can use it to execute code that you want to run each time a module is loaded, or specify the submodules to be exported.
